version: 2
before:
  hooks:
    - go mod download
builds:
  - id: simplemq-cli
    env:
      - CGO_ENABLED=0
    main: ./cmd/simplemq-cli/
    binary: simplemq-cli
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
  - id: simplemq-localserver
    env:
      - CGO_ENABLED=0
    main: ./cmd/simplemq-localserver/
    binary: simplemq-localserver
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
release:
  use_existing_draft: true
checksum:
  name_template: "checksums.txt"
archives:
  - id: simplemq-cli
    ids:
      - simplemq-cli
    name_template: "simplemq-cli_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
  - id: simplemq-localserver
    ids:
      - simplemq-localserver
    name_template: "simplemq-localserver_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
snapshot:
  version_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
